
### Create a new order
POST http://localhost:3000/orders
content-type: application/json

{
    "buyerId": "5c7b6f00-367d-471d-bfcc-6485258f105e",
    "orderDetail": {
        "productName": "양말",
        "quantity": 1000,
        "unitPrice": 10000,
        "color": "white",
        "size": "xl",
        "dueDate": "20251128"
    }
}

### Confirm Order
POST http://localhost:3000/orders/3786ae1f-00b5-43cb-b4af-e140c651ce65/confirm
content-type: application/json

{
    "employeeId": "f562cf1a-e75a-4dd8-ac87-bdbddf5b09dd"
}

### Update order
PATCH http://localhost:3000/orders/3786ae1f-00b5-43cb-b4af-e140c651ce65
content-type: application/json

{
    "buyerId": "5c7b6f00-367d-471d-bfcc-6485258f105e",
    "orderDetail": {
        "quantity": 20000,
        "unitPrice": 15000,
        "color": "green"
    }
}




### Reject Order 
POST http://localhost:3000/orders/3786ae1f-00b5-43cb-b4af-e140c651ce65/reject
content-type: application/json

{
    "employeeId": "f562cf1a-e75a-4dd8-ac87-bdbddf5b09dd	"
}


### 일반 조회
GET http://localhost:3000/orders/3786ae1f-00b5-43cb-b4af-e140c651ce65

### 버전간 비교
GET http://localhost:3000/orders/3786ae1f-00b5-43cb-b4af-e140c651ce65?fromVersion=1&toVersion=3

### 특정 버전 조회
GET http://localhost:3000/orders/3786ae1f-00b5-43cb-b4af-e140c651ce65?version=1

### 특정 시점 조회
GET http://localhost:3000/orders/3786ae1f-00b5-43cb-b4af-e140c651ce65?timestamp=1764409607


